
export const SET_USER_INFO_LIST = 'userHomePage/SET_USER_INFO_LIST'
export const UPDATE_USER_INFO_LIST = 'userHomePage/UPDATE_USER_INFO_LIST'


export const SET_PRIVATE_MASSAGES = 'rightView/SET_PRIVATE_MASSAGES'
export const ADD_PRIVATE_MASSAGES = 'rightView/ADD_PRIVATE_MASSAGES'
export const SET_NEW_MASSAGES = 'rightView/SET_NEW_MASSAGES'
export const ADD_PRIVATE_CHAT = 'rightView/ADD_PRIVATE_CHAT'
export const DELETE_PRIVATE_CHAT = 'rightView/DELETE_PRIVATE_CHAT'
export const DELETE_PRIVATE_MASSAGES = 'rightView/DELETE_PRIVATE_MASSAGES'